repos:
  - repo: local
    hooks:
      id: lint
      name: Linter
      stages: [pre-commit, pre-merge-commit, manual]
      entry: "scripts/lint.sh"
      language: python
      types: [python]
      require_serial: true
      verbose: true

  - repo: local
    hooks:
      - id: static-analysis
        name: Static analysis
        entry: "scripts/static-analysis.sh"
        language: python
        types: [python]
        require_serial: true
        verbose: true
