repos:
  - repo: local
    hooks:
      id: lint
      name: Linter
      entry: ruff check .
      language: python
      types: [python]

  - repo: local
    hooks:
      - id: static-analysis
        name: Static analysis
        entry: isort .
        language: python
        types: [python]
